users:
  - name: alice-backend
    email: lucerianovern+alice@gmail.com
    github_team: backend
    aws_account: dev
    aws_groups:
      - developers
    role: engineer

  - name: bob-backend
    email: lucerianovern+bob@gmail.com
    github_team: backend
    aws_account: prod
    aws_groups:
      - developers
    role: engineer

  - name: carol-backend
    email: lucerianovern+carol@gmail.com
    github_team: backend
    aws_account: prod
    aws_groups:
      - developers
      - admins
    role: lead

  - name: marky-frontend
    email: veronica.luceriano+markybap@gmail.com
    github_team: frontend
    aws_account: dev
    aws_groups:
      - developers
    role: engineer
